### ISSUE TITLE
Ajustar el Readme del Cliente

### ISSUE THREAD

**Issue by grumysh** [udistrital/movilidad_academica_cliente#1]
Crear,Ajustar y complementar `README.ME` del repositorio teniendo en cuenta los lineamientos de la oficina:
Basarse en - [Contenido README](https://github.com/udistrital/introduccion_oas/blob/master/repositorios_institucionales/contenido_readme.md)

- [x] Adjuntar al archivo  `README` los procedimientos para correr el proyecto
- [x] Adjuntar al archivo  `README` la información relacionada a las dependencias usadas
- [x] Adjuntar al archivo  `README` información relacionada a herramientas usadas para su creación
- [x] Adjuntar al archivo  `README` información relacionada a las variables de entorno
- [ ] Adjuntar al archivo  `README` los entitys relacionados
- [ ] Adjuntar al archivo  `README` información relacionada a las vistas y `archivos.json` que las construyen
- [ ] Adjuntar al archivo  `README` la paleta de colores usada para su personalización
- [ ] Adjuntar al archivo  `README` método bajo el que la aplicativo se conecta a su -MID respectivo

**Calidad**

- [x] El archivo `README` cuenta con la información necesario para replicar la creación del proyecto
- [x] El archivo `README` cuenta con los entitys usados para generación del proyecto
- [x] El archivo `README` cuenta con información detallada de como se relacionan las vistas a los archivos que las construyen
- [x] El archivo `README` cuenta con la información respectiva a los cambios de estilo 
- [x] El archivo `README` cuenta con información respectiva a las tecnologias que implementa, herramientas sobre las que se basa
- [x] El archivo `README` explica donde se deben mantener las variables de entorno
- [x] El archivo `README` explica como se conecta el aplicativo contenido cliente con su -MID respectivo
- [x] El archivo `README` con su debido licensamiento
- [x] El archivo `README` sigue los lineamientos para la Documentación

**Comment by BOTOOM** [comment]
segun poker planning se define un estimado de 3 horas
