### ISSUE TITLE
Generar e implementar vista de convenios en el cliente

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/movilidad_academica_cliente#13]
- [x] segun los mockups #6 crear los entitys para la generacion de la vista.
- [x] generacion de la vista con el generador [ngx-generator](https://github.com/BOTOOM/ngxGenerator).
- [x] integración de la vista generada al cliente
- [x] ajuste de endpoints , con el fin de poder visualizar los datos en la tabla

**Comment by Soulfilip-UD** [comment]
Issue terminado y completado!
