### ISSUE TITLE
Lograr Build de la aplicación

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/movilidad_academica_cliente#21]
Por adelantar trabajo y realizar buenas practicas debemos lograr el build de la aplicación

- [ ] Lograr el build sin errores de url
**Calidad**

- [ ] Se logra exportar el build de la aplicación

**Comment by ManuelMurillo** [comment]
El error del build se esta generando por una URL malformada o invalida en la configuracion del archivo app-conifg.ts. es necesario mas tiempo para hecer una depuracion en el archivo de configuracion

**Comment by ManuelMurillo** [comment]
El error se debe a que en el modo de producción los archivos de distribucion deben ser consumidos a travez de un servidor.
