### ISSUE TITLE
Estilización de la Plataforma(Cliente)

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/movilidad_academica_cliente#4]
Basados en el la paleta de colores del CERI crear la relacionada al proyecto e hacer los cambios respectivos en la plantilla.

- [x] Revisar las paletas de colores que maneja el CERI y la U.Distrital en sus aplicativos

- [x] Proponer una paleta de colores personalizadas para el aplicativo

- [x] Modificar la plantilla para aplicar los colores escogidos

**Calidad**

- [x] Existe un estudio previo para la paleta de colores de la plataforma
- [x] La paleta de colores usada en el aplicativo guarda similitud a los portales del CERI, es comoda y mantiene una buena apariencia
- [x] La paleta de colores usada fue documentada en el `README`, comentando la ubicación del archivo para su modificación
- [x] La paleta de colores es del gusto del cliente

**Comment by BOTOOM** [comment]
4 horas para realizarce

**Comment by Soulfilip-UD** [comment]
Paleta Colores Plataforma UDistrital General:
![PaletaUDistrital](https://user-images.githubusercontent.com/50924615/58441224-3bddc300-811b-11e9-946d-0e4e0c9b1f0d.png)

**Comment by Soulfilip-UD** [comment]
Paleta Colores Plataforma CERI: ceri.udistrital.edu.co
![PaletaCERI](https://user-images.githubusercontent.com/50924615/58441234-4bf5a280-811b-11e9-894e-385e35775d05.png)

**Comment by Soulfilip-UD** [comment]
Paleta Propuesta Plataforma Movilidad CERI:
![PaletaMovilidad](https://user-images.githubusercontent.com/50924615/58441246-5c0d8200-811b-11e9-8cd0-d21a63977dd8.png)

**Comment by Soulfilip-UD** [comment]
Me base en esta documentación para los cambios de colores que no aprecen por defecto en la estilización del tema : https://akveo.github.io/nebular/docs/themes/cosmic#color-fg-highlight
