### ISSUE TITLE
Ejecucion del repositorio CERI

### ISSUE THREAD

**Issue by FelipeVel** [udistrital/movilidad_academica_cliente#49]
[Repositorio CERI](https://github.com/udistrital/ceri)

- [x] Clonar el repositorio en un entorno locaL.
- [x] Hacer la instalación de las dependencias del proyecto para poder ejecutarlo de manera correcta.
- [x] Instalar Angular de manera global en el entorno virtual para no tener inconvenientes con los comandos como ng serve.
- [x] Ejecutar en el framework de preferencia y acceder a http://localhost:4200 para tener acceso al recurso.
- [x] Inspeccionar el código y la página mostrada.

**Comment by JQuinteroC** [comment]
node v14.17.1 no reconoce angular al ejecutar 
`npm install`

**Comment by JQuinteroC** [comment]
Se hace uso de node version manager (**nvm**) para instalar node v6.10, permitiendo reconocer los comandos de angular y poder iniciar el servidor
![Instalación de la versión requerida para correr Angular-cli](https://user-images.githubusercontent.com/21268124/123717278-224f5e00-d842-11eb-9ff6-ebc1c0c3fa80.png)

Dando como resultado la ejecución adecuada en el puerto 4200 sin modificar los package.json del proyecto

![Ejecución del [repositorio CERI](https://github.com/udistrital/ceri) en maquina local ](https://user-images.githubusercontent.com/21268124/123717403-62aedc00-d842-11eb-8c0a-85e5988c1c8e.png)
