### ISSUE TITLE
Mockups de la Aplicaciòn (Cliente)

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/movilidad_academica_cliente#6]
Realizar los mockups referentes a la aplicación:

- [x] Teniendo en cuenta la arquitectura base de ngx-Admin, dar inicio a los mockups

- [x] Graficar en los mockups las interfaces que el usuario encontrara en la aplicación

- [x] De ser posible mostrar en los mockups la experiencia de Usuario al revisar cada elemento

**Calidad**

- [x] Los mockups realizados son alcanzables a realizar y basados en la arquitectura de ngxAdmin

- [x] En los mockups se distiguen cada interface con la que los usuarios interactuaran

- [x] En los mockups se distiguen las animaciones y acciones de los distintos elementos en pantalla

- [x] Los mockups cumplen con la historia de Usuario #--

- [x] Los mockups son documentados

**Comment by BOTOOM** [comment]
se definen 4 horas para los mockups

**Comment by Soulfilip-UD** [comment]
![General](https://user-images.githubusercontent.com/50924615/58438359-70e11a00-8109-11e9-944d-ad4582395b66.png)
![Form](https://user-images.githubusercontent.com/50924615/58438360-72124700-8109-11e9-9204-7456c7faf360.png)

Mockup Formulario y Elementos Generales de la Aplicación

**Comment by Soulfilip-UD** [comment]
![Listado](https://user-images.githubusercontent.com/50924615/58440738-4ac27680-8117-11e9-8e78-ab04d6416c54.png)
