### ISSUE TITLE
Formato JSON (Client) -> CRUD Movilidad

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/movilidad_academica_cliente#7]
Una vez que `~_MID` tenga establecido el formato de los `archivos.json` , crear los métodos para realizar las peticiones (GET/POST/PUT).

- [ ] Contar con la documentación referente al formato de los `archivo.json` del componente `~_MID`

- [ ] Generar las Pruebas Unitarias para recibir e enviar información al componente `~_MID`

- [ ] Generar los Métodos (GET/POST/PUT) con los que realizaran las peticiones

- [ ] De ser posible, implementar `Reducers` para la información que se puede guardar en cache

**Calidad**

- [ ] Existen y son satisfactorias las pruebas unitarias al interactuar con el API
- [ ] Se cuenta con toda la información exigida en los formularios y/o vistas de los estudiantes o docentes Entrantes
- [ ] Se cuenta con toda la información exigida en los formularios y/o vistas de los estudiantes o docentes Salientes

- [ ] Se implementan `Reducers` para la información que puede guardarse en cache

- [ ] Los métodos implementados quedan documentados y conservan un buen estandar de código escrito

**Comment by BOTOOM** [comment]
cambiar nombre del issue

**Comment by BOTOOM** [comment]
se definen 6 horas para ajustar los endpoints

**Comment by Soulfilip-UD** [comment]
El issue abarca demasiados procesos por debajo por lo que se particiona y se cierra el Issue
