### ISSUE TITLE
Ocultar Botones Innecesarios

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/movilidad_academica_cliente#8]
Ocultar los botones y acciones referentes al cambio de temas, estilos y maquetación de la información.

- [x] Identificar todos los botones referentes al cambio de estilos, temas y plantillas

- [x] Realizar pruebas unitarias que comprueben que no existen tales botones en pantalla

- [x] Ocultar los botones , menus que permitan el cambio de tema,plantillas

**Calidad**

- [x] El usuario no puede realizar cambios en la plantilla o estilos

**Comment by BOTOOM** [comment]
se definen 2 horas para su realizacion
