### ISSUE TITLE
Autenticación WSO2 (Cliente)

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/movilidad_academica_cliente#9]
La aplicación requiere identificarse con el servicio WSO2 para adquirir un token de sesion el cual permitira el acceso a las funcionalidades de la Aplicación

- [ ] Leer Documentación para autenticación con el WSO2

- [ ] Realizar Pruebas Unitarias de Autenticación con en WSO2

- [ ] Al dar click en Iniciar Sesión redirigir a la plataforma del WSO2

- [ ] Una vez que el usuario se loguee y regrese con un token de identificación, guardarlo en una cookie 

**Calidad**

- [ ] Se realizan pruebas satisfactorias al login  del servicio WSO2

- [ ] La plataforma cuenta con un link  'Iniciar Sesión' el cual redirige a la plataforma del WSO2

- [ ] Despues de loguearse y ser redirigido por el WSO2 , el usuario adquiere una cookie de sesión

- [ ] El usuario adquiere acceso a las funcionalidades de la aplicación

**Comment by BOTOOM** [comment]
función pospuesta debido a que se necesita un id propio para la plataforma del ceri en wso2
